.TH SIMEIS 1 "19 Juin 2026" "0.1.9" "Simeis Manual"
.SH NAME
simeis \- Serveur de jeu spatial par API
.SH SYNOPSIS
.B simeis-server
.SH DESCRIPTION
.B simeis-server
lance le serveur de jeu Simeis sur le port 8081. Les joueurs peuvent s'y connecter via HTTP.
.SH SEE ALSO
cmatrix(1)
.SH AUTHOR
Mathis BESSON, Adam EPIARD, Nathan PIVETEAU