name: Analyse avancée du code

on:
  pull_request:
    types: [closed]
    branches:
      - "release/**"

jobs:
  functional-test-skeleton:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Installer Rust stable
        run: |
          rustup toolchain install stable --profile minimal
          rustup default stable

      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ~/.cargo/bin/
            target/
          key: ${{ runner.os }}-cargo-analysis-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-analysis-
            ${{ runner.os }}-cargo-

      - name: Compiler en debug avec heavy-testing
        run: cargo build -p simeis-server --features heavy-testing

      - name: Lancer les tests unitaires avec heavy-testing
        run: cargo test -p simeis-server --features heavy-testing

      - name: Installer cargo-audit
        run: command -v cargo-audit >/dev/null || cargo install cargo-audit --locked

      - name: Auditer les dependances avec cargo-audit
        run: cargo audit

      - name: Installer nightly + rust-src pour cargo-udeps
        run: rustup toolchain install nightly --profile minimal --component rust-src

      - name: Installer cargo-udeps
        run: command -v cargo-udeps >/dev/null || cargo +nightly install cargo-udeps --locked

      - name: Verifier les dependances inutiles avec cargo-udeps
        run: cargo +nightly udeps --workspace --all-targets

      - name: Lancer les tests property-based (Version lourde - 60 secondes)
        run: python3 tests/propertybased.py 60

      - name: Lancer le script Python de tests fonctionnels
        run: |
          pip3 install requests
          python3 tests/functional_tests.py

      - name: Vérifier que le script s'est bien exécuté
        if: success()
        run: echo "Execution du script Python OK."
