name: DIY Dependabot

on:
  schedule:
    - cron: '50 12 * * *'
  workflow_dispatch:
  push:
    branches:
      - test-ci-nathan

permissions:
  contents: write
  pull-requests: write

jobs:
  update-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install cargo-update
        run: cargo install cargo-update

      - name: Update dependencies
        run: cargo update

      - name: Create Pull Request with gh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "bot"
          git config user.email "bot@github.com"
          
          BRANCH="bot/update"
          git checkout -b $BRANCH
          git add Cargo.lock
          
          # Si il y a des changements on commit et on push
          if ! git diff --staged --quiet; then
            git commit -m "Update dependencies"
            git push -f origin $BRANCH
            
            # On cree la PR, si elle existe deja gh va afficher une erreur et continuer (grace a || true)
            gh pr create --title "Update dependances" --body "Mise a jour auto" --label "bot/update" --base main --head $BRANCH || true
          fi
