name: DIY Dependabot

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ~/.cargo/bin/
          key: ${{ runner.os }}-cargo-dependabot-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-dependabot-
            ${{ runner.os }}-cargo-

      - name: Install cargo-update
        run: command -v cargo-install-update >/dev/null || cargo install cargo-update

      - name: Update all dependencies
        run: |
          cargo update
          cargo update --manifest-path example/rust/Cargo.toml || true
          cargo update --manifest-path sdk/rust/Cargo.toml || true

      - name: Create Pull Request with gh
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          BRANCH="bot/update"
          git checkout -b $BRANCH
          git add -u
          
          # Si il y a des changements on commit et on push
          if ! git diff --staged --quiet; then
            git commit -m "Update dependencies"
            git push -f origin $BRANCH
            
            # Vérifier si une PR est déjà ouverte
            PR_OPEN=$(gh pr list --head "$BRANCH" --state open --json number --jq '.[0].number')
            
            if [[ -z "$PR_OPEN" || "$PR_OPEN" == "null" ]]; then
              gh pr create --title "Update dependances" --body "Mise a jour auto" --base main --head "$BRANCH" || echo "⚠️ Impossible de créer la PR"
            else
              echo "Une PR est déjà ouverte : #$PR_OPEN"
            fi
          fi
