name: DIY Dependabot

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install cargo-update
        run: cargo install cargo-update

      - name: Update all dependencies
        run: |
          cargo update
          cargo update --manifest-path example/rust/Cargo.toml || true
          cargo update --manifest-path sdk/rust/Cargo.toml || true

      - name: Create Pull Request with gh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          BRANCH="bot/update"
          git checkout -b $BRANCH
          git add '**/Cargo.lock'
          
          # Si il y a des changements on commit et on push
          if ! git diff --staged --quiet; then
            git commit -m "Update dependencies"
            git push -f origin $BRANCH
            
            # S'il n'y a pas de PR ouverte, on en crée une ou on en ré-ouvre une existante.
            if [[ -z "$(gh pr list --head "$BRANCH" --state open --limit 1)" ]]; then
              CLOSED_PR_NUM=$(gh pr list --head "$BRANCH" --state closed --jq '.[0].number')
              if [[ -n "$CLOSED_PR_NUM" && "$CLOSED_PR_NUM" != "null" ]]; then
                gh pr reopen "$CLOSED_PR_NUM"
              else
                gh pr create --title "Update dependances" --body "Mise a jour auto" --base main --head "$BRANCH"
              fi
            fi
          fi
