name: Vérification du formatage Python

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - '**' 

jobs:
  check-format:
    name: Lint et Format avec Ruff
    runs-on: ubuntu-latest

    steps:
      - name: Récupération du code
        uses: actions/checkout@v6

      - name: Installation de Ruff
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install ruff

      - name: Exécution de Ruff sur les fichiers Python
        run: |
          ruff format --check tests/
          ruff check --output-format=github tests/